WIDTH, HEIGHT = 800, 800
BOARD_COLOR = (0, 100, 0)
WHITE_COLOR = (255, 255, 255)
BLACK_COLOR = (0, 0, 0)
DARKGRAY = (169, 169, 169)
BLACK = 1
WHITE = -1
EMPTY = 0
ROWS = 8
COLS = 8
# board = [[EMPTY for col in range(COLS)] for row in range(ROWS)]
board = [
    [WHITE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WHITE],
    [WHITE, WHITE, EMPTY, EMPTY, WHITE, EMPTY, EMPTY, WHITE],
    [WHITE, EMPTY, WHITE, EMPTY, EMPTY, EMPTY, EMPTY, WHITE],
    [WHITE, WHITE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WHITE],
    [WHITE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WHITE],
    [WHITE, WHITE, WHITE, EMPTY, WHITE, EMPTY, EMPTY, WHITE],
    [WHITE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WHITE],
    [WHITE, EMPTY, WHITE, EMPTY, EMPTY, WHITE, EMPTY, WHITE],
]
board[3][3] = WHITE
board[3][4] = BLACK
board[4][3] = BLACK
board[4][4] = WHITE
SQUARE_SIZE = WIDTH // COLS
PIECE_RADIUS = SQUARE_SIZE // 2 - 5
